method: demo
training:
  out_dir:  out/default
  batch_size: 64
  print_every: 10
  visualize_every: 2000
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 100000
  eval_sample: false
  model_selection_metric: loss
  model_selection_mode: minimize
test:
  threshold: 0.5
  model_file: model_best.pt
generation:
  batch_size: 100000
  generation_dir: generation
preprocessor:
  type: null
  config: ""
  model_file: null
